version: '3.8'

volumes:
  mongodb_data:

services:
  database:
    image: mongo:6.0
    restart: always
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  datadock:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5050:5050"  # expose app on port 80 for production
    env_file: .env
    environment:
      - MONGODB_URI
      - DATABASE_NAME
      - NEXT_PUBLIC_API_URL
      - OPENAI_SECRET_KEY
      - NEXT_PUBLIC_HIDE_AI
      - NEXT_PUBLIC_HIDE_UPLOADER_BUTTONS
      - NEXT_PUBLIC_HIDE_ADMIN_REGEX_AI
      - OPENROUTER_URL
      - OPENROUTER_API_KEY
      - REDIS_URL
      - NODE_ENV
      - SESSION_SECRET
    depends_on:
      - database
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
