version: '3.8'

volumes:
  mongodb_data:

services:
  database:
    image: mongo:6.0
    restart: always
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  datadock:
    image: datadock/datadock:latest
    restart: always
    ports:
      - "80:5050"  # expose app on port 80 for production
    environment:
      MONGODB_URI: mongodb://database:27017/DataDock
      DATABASE_NAME: 'DataDock'
      OPENAI_SECRET_KEY: your-openai-secret-key
      NEXT_PUBLIC_API_URL: 'http://172.17.0.1'  # or use nginx reverse proxy
    depends_on:
      - database
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
